### ISSUE TITLE
Implement common non-raw-mode keyboard shortcuts

### ISSUE THREAD

**Issue by pzmarzly** [sigmaSd/IRust#1]
In other REPLs `Ctrl+D` closes REPL if buffer is empty. Also, `Ctrl+Z` can be used to send it to background (via `SIGTSTP`). I noticed you are putting the terminal in raw mode, I'm not sure if it is necessary (do other REPLs do that, too?). Isn't there any other way to get Up and Down keypresses? Just asking, I genuinely don't know.

**Comment by sigmaSd** [comment]
1- So is it as simple as chaning `ctrl+C` to `ctrl+D` or I'm missing something
2- for Ctrl+Z I'll check it out but my main concern is how hard is it to mimic the same behavior on windows
3- for raw mode is there a disadvantage on using it?, the problem without using it the terminal will immediately print the keys for example arrow keys will be printed immediately like `^[[D`

**Comment by pzmarzly** [comment]
I have no idea how other REPLs do it, but when I e.g. open `python3` in terminal, it doesn't print weird characters, yet Ctrl+Z works. But unless you manage to find some "proper" way (my google-fu is not enough to quickly find anything), I'm fine with leaving raw mode and adding:

- `Ctrl+D` as `if self.buffer.empty() { self.exit()?; }`
- Unix-only `Ctrl+Z` as `nix::sys::signal::kill(nix::unistd::Pid::this(), Some(nix::sys::signal::Signal::SIGTSTP))?`

**Comment by sigmaSd** [comment]
Thanks a lot for the suggestions!
Feel free to open PRs btw
fixed in https://github.com/sigmaSd/IRust/commit/20cda4ce376cbb00f1ea66e34921a67437a85b69

**Comment by pzmarzly** [comment]
I will in a second, especially since what you've done is not exactly what I had in mind (though I don't mean any offence, it's still awesome that you replied that fast)
