### ISSUE TITLE
typing twice in windows with crossterm-0.26+

### ISSUE THREAD

**Issue by viruscamp** [sigmaSd/IRust#109]
crossterm-0.26 introduce a new feature [Support key release events for windows](https://github.com/crossterm-rs/crossterm/pull/745)   which makes irust typing twice in windows.

See  
https://github.com/crossterm-rs/crossterm/issues/752  
https://github.com/helix-editor/helix/issues/6133  

And this is a fix method: https://github.com/helix-editor/helix/pull/6139

**Comment by sigmaSd** [comment]
Hello, thanks for investigating this, do you mind opening a PR, I don't have windows to test

**Comment by viruscamp** [comment]
> Hello, thanks for investigating this, do you mind opening a PR, I don't have windows to test

OK, PR made.
