### ISSUE TITLE
Rust analyzer is not working on Windows

### ISSUE THREAD

**Issue by AddictArts** [sigmaSd/IRust#118]
How do you check enabled?

I reset the config using `irust --reset-config`

I see the settings that match the README.

Helix lsp rust-analyzer works on Windows for me.

Thanks

**Comment by AddictArts** [comment]
I see rust-analyzer runnning as a child process. When it starts it says everything is good. Are you using Crossterm?

**Comment by AddictArts** [comment]
It seems the pop up text is not showing, unless there is a magic key combo to see that.

**Comment by AddictArts** [comment]
LOL, Tab, oops apologies.

**Comment by sigmaSd** [comment]
Maybe you expected the completion to auto trigger like editors, for now it needs to be manually triggered with tab

**Comment by AddictArts** [comment]
Correct, especially due to the reference in the original issue to how helix does it, but I understand that was more an implementation and not the ux. Thanks it works fairly well and makes IRust an interesting tool.

**Comment by sigmaSd** [comment]
thanks
