### ISSUE TITLE
Interactive usage

### ISSUE THREAD

**Issue by robert-dzikowski** [sigmaSd/IRust#119]
I followed your example on https://sigmasd.github.io/irust_book/interactive-usage/
```
cargo new --lib irustlib
cd irustlib
irust
In: :add .
In: use irustlib::*;
error[E0432]: unresolved import `irustlib`
 --> src\main.rs:3:5
  |
3 | use irustlib::*;
  |     ^^^^^^^^ use of undeclared crate or module `irustlib`

```
Can you help me, please?

**Comment by sigmaSd** [comment]
it should be `:add --path .`

I should update the docs

**Comment by robert-dzikowski** [comment]
I use Windows 10 and your prebuild binary https://github.com/sigmaSd/IRust/releases/download/irust%401.70.0/irust-irust@1.70.0-x86_64-pc-windows-msvc.zip.

**Comment by robert-dzikowski** [comment]
It works thanks.
