### ISSUE TITLE
Racer should not autocomplete `::command`s

### ISSUE THREAD

**Issue by pzmarzly** [sigmaSd/IRust#12]
Right now Racer autocompletes `::commands` as if they were Rust expression (`::` is namespace root). Meanwhile, IRust uses them as bash commands. In the screenshot below, I'm trying to write `::ls`:

![Screenshot from 2019-05-22 21-19-01](https://user-images.githubusercontent.com/8074163/58202232-3fb2b500-7cd7-11e9-86de-f5b5b1a921f0.png)

**Comment by sigmaSd** [comment]
https://github.com/sigmaSd/IRust/commit/6c2f4e3dbe6ebdf0ef545bc5ca3517c70f06fc81
Now racer completes IRust commands and ignores shell commands
Thanks a lot as usual !

**Comment by pzmarzly** [comment]
I think you wanted to name the function `write_suggestion`, not `write_sggestion`. :)

**Comment by sigmaSd** [comment]
yep xD
