### ISSUE TITLE
cargo-edit requires --path argument for a local dependency after version 0.9.1

### ISSUE THREAD

**Issue by veer66** [sigmaSd/IRust#125]
cargo_add function and cargo_add_sync function generate cargo add /local/path/to/project. However, after cargo-edit 0.9.1, it require a --path argument, for example, cargo add --path /local/path/to/project.

**Comment by sigmaSd** [comment]
Hello, thanks for the issue/pr

You can already pass arguments to `:add`, so you can use `:add --path .` (it works with relative path as well)

But I noticed when used incorrectly (like `:add .`) its not showing an error, I'll add a commit to fix that

**Comment by sigmaSd** [comment]
The error should now appear when used incorrectly  https://github.com/sigmaSd/IRust/commit/702fd9f8cbdc3717547c14ed3c7ddd1a497037ca

Also I add it to the docs https://github.com/sigmaSd/IRust/commit/1bfbb7476a2b78b9b333262d64ea9aed7f388c4c
