### ISSUE TITLE
Option to specify config.toml path

### ISSUE THREAD

**Issue by vsndev3** [sigmaSd/IRust#134]
Is it possible to have a command line option to specify config.toml path or a global config that takes a user specified directory as root for all configuration. This way the IRust can be packed and shared as a single self-contained directory (planning rust tool chain + zig for compiler)

**Comment by sigmaSd** [comment]
There are a couple of places that uses the host system

![image](https://github.com/sigmaSd/IRust/assets/22427111/d371d69e-a186-4e25-b964-b70f2705c7a6)

Also the repls are stored in host temporary directory (and some commands like :dbg uses it)

![image](https://github.com/sigmaSd/IRust/assets/22427111/d64e23cc-2e65-4a58-9721-009a1ebb86f4)

I'm not sure if there is a compelling enough usecase to warrent to make all those configurable, though its not that big of a change

irust can be already shared as self contained binary but I think you mean a binary that doesn't use the host system, but there is a flatpak build that does this already https://flathub.org/apps/io.github.sigmasd.IRust

**Comment by vsndev3** [comment]
Thanks for the response. For me its an embedded environment, so flatpack cannot be used. However please consider something like https://github.com/rust-cli/confy where config can be loaded first from local dir if not load from system specific path. I guess I have to patch my local repo for now.

**Comment by sigmaSd** [comment]
I see, lets keep this open, either way the code changes shouldn't be that big so I don't have a big problem adding this feature, feel free to open a pr

I prefer to not add a dependencies on confy, this feature is simple enough, it can be coded here

**Comment by sigmaSd** [comment]
@vsndev3 I added this feature in this branch https://github.com/sigmaSd/IRust/compare/idirs?expand=1

All the paths used by irust are configurable with env variables

If that works for you I can merge this

**Comment by vsndev3** [comment]
It works perfectly,  Thanks

**Comment by sigmaSd** [comment]
I pushed irust 1.71.22 with this patch
