### ISSUE TITLE
Navigating long lines using Ctrl+Left, Ctrl+Right

### ISSUE THREAD

**Issue by pzmarzly** [sigmaSd/IRust#14]
It is useful to jump over whole words. I think it could be implemented like this:

When hitting `Ctrl+Left`:
- if character left to the cursor is a letter, skip to first non-letter left to the cursor
- if character left to the cursor is not a latter, skip to first letter left to the cursor

In case of `Ctrl+Right`, everything is the same but `s/left/right`. I'm not sure if this is how it's done in other REPLs, I never paid attention to how exactly cursor jumps, but I think it would be quite sane behavior (actually more sane than some IDEs offer, when I think about it).

**Comment by sigmaSd** [comment]
Currently https://github.com/TimonPost/crossterm doesn't expose those keys, I forked it and made a simple hack, basicly consider ctrl +arrow, alt+arrow, shift +arrow the same, so I can implement this, https://github.com/sigmaSd/IRust/tree/ctrlarrow What do you think should I use this on master?

**Comment by pzmarzly** [comment]
In my opinion you should open an issue at crossterm, but for now go with your fork. I think you can filter ctrl+arrow by checking whole CSI sequence - as explained [here](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#input-sequences), you can match line `ESC [ 1 ; 5 D` for Ctrl+Left instead of just matching `ESC [ ... D` like the code is doing now.

**Comment by sigmaSd** [comment]
Thanks a lot for the infos!, I filed a PR as you suggested. 
Unfortunately I cant publish IRust with a git dependency, so for now `Ctrl` key will be hidden in the published version.

**Comment by sigmaSd** [comment]
Implemented on maser will merge to the published version once crossterm adds the PR
