### ISSUE TITLE
Logo missing on Jupyter lab launcher page

### ISSUE THREAD

**Issue by eunos-1128** [sigmaSd/IRust#141]
I noticed Rust's logo is missing on Jupyter lab launcher page.

I think showing logo will make IRust look better.

**Comment by eunos-1128** [comment]
I opened #140

**Comment by sigmaSd** [comment]
thanks, this is now fixed in irust_kernel 0.3.1 https://pypi.org/project/irust-kernel/0.3.1/

**Comment by eunos-1128** [comment]
@sigmaSd 

Thanks for dealing with promptly.
