### ISSUE TITLE
Flush stdout so there's feedback when a user hits enter

### ISSUE THREAD

**Issue by actuday6418** [sigmaSd/IRust#143]
![a](https://github.com/user-attachments/assets/fea3c7cd-7aa6-432a-a328-2b61da316e4d)

Feels like bad UX when you hit enter and nothing happens during when the command is compiled/executed.
Flushing stdout at `irust/src/engine.rs:207` seems to fix this.

PS: Open GIF in a new tab

**Comment by sigmaSd** [comment]
Thanks for the feedback, seems reasonable, pr is welcome

**Comment by sigmaSd** [comment]
fixed in https://github.com/sigmaSd/IRust/commit/5a7e32e2ef4e360d9aa2855273452752676f92d4
