### ISSUE TITLE
Wrong macOS configuration path

### ISSUE THREAD

**Issue by yo-goto** [sigmaSd/IRust#147]
First of all, it seems that the config path for macOS in the README is incorrect. I checked the real path by using `irust -h`.

```
wrong: /Users/$USER/Library/Preferences/irust/config.toml 

correct: /Users/$USER/Library/Application Support/irust/config.toml
```

As mentioned above, the location of the path on macOS being in `Application Support`, which is not very user-friendly, is problematic. I feel that many macOS users prefer to place their config files under `~/.config/`. For example, tools like Nushell default to placing config files in `Application Support`, but [some users are dissatisfied with this setup](https://github.com/nushell/nushell/issues/8256).

Personally, I think the best approach is the one used by [Alacritty](https://github.com/alacritty/alacritty?tab=readme-ov-file#configuration), where config files are searched for in the following locations. Would it be possible to adopt a similar configuration setup?

```
$XDG_CONFIG_HOME/alacritty/alacritty.toml
$XDG_CONFIG_HOME/alacritty.toml
$HOME/.config/alacritty/alacritty.toml
$HOME/.alacritty.toml
```

**Comment by sigmaSd** [comment]
I updated the readme with the real path, If you want to change the location that's ok with me (I don't use mac so I don't have a strong opinion here) , feel free to open a PR 
In the mean times you can use these variables to change where the configuration is located 
![image](https://github.com/user-attachments/assets/8d19a4d3-32d8-45e8-aee7-c8ee93d3df2a)

**Comment by sigmaSd** [comment]
For the the second issue you mentioned: if you close all instances of irust, then modify the config files then open irust, it should work , otherwise its a new bug
the issue you're seeing is probably https://github.com/sigmaSd/IRust/issues/142

**Comment by yo-goto** [comment]
Yes, after closing an instance of irust, editing the configuration file, and then launching irust again, the modified settings are not applied. Upon opening the configuration file again, it is confirmed to have reverted to the default settings.

**Comment by sigmaSd** [comment]
Then it's a different bug but I can't reproduce on Linux, so this might take some time to get fixed.

**Comment by sigmaSd** [comment]
I can't reproduce on mac os, maybe check if you're using the latest version of irust

 (Darwin Mac-1734887902455.local 23.6.0 Darwin Kernel Version 23.6.0: Fri Nov 15 15:13:40 PST 2024; root:xnu-10063.141.1.702.7~1/RELEASE_ARM64_VMAPPLE ar
m64) 

[tt.webm](https://github.com/user-attachments/assets/42dc6792-d2a6-4da1-9c85-fd0c760192d8)

**Comment by yo-goto** [comment]
I've checked the latest version, and it works. Thank you.
