### ISSUE TITLE
Line overflows incorrectly

### ISSUE THREAD

**Issue by pzmarzly** [sigmaSd/IRust#16]
This is how IRust looks with `std::process::Command::new("").output().unwrap_err().description().to_string()` when it ran out of terminal space:

![Screenshot from 2019-05-22 21-35-00](https://user-images.githubusercontent.com/8074163/58203175-d3858080-7cd9-11e9-9493-f07755ef70f6.png)

The `g(` part was lost somewhere (it is in the buffer, but not displayed), old autocompletion is still here, new line is unexpected.

**Comment by sigmaSd** [comment]
@pzmarzly Would be great if you checkout master version, this updates needs a lot of testing.

**Comment by pzmarzly** [comment]
After text is removed, line counter is not decreased. For example, here I wrote 2 lines, went to the start, removed some text and hit End:

![Screenshot from 2019-05-26 20-32-01](https://user-images.githubusercontent.com/8074163/58385749-79e0c700-7ff5-11e9-9dc2-db5f1a0b90a8.png)

It behaves like there are still 2 lines.

Then there are also times when Racer no longer triggers in second line, but that's minor.

**Comment by sigmaSd** [comment]
@pzmarzly nice catch! hopefully its better now https://github.com/sigmaSd/IRust/commit/5ef460af092f42f61077d1789cc644b87b42a462

**Comment by sigmaSd** [comment]
Should be good now. Feel free to reopen in case of more overlooked issues
