### ISSUE TITLE
Add debounce to racer calls

### ISSUE THREAD

**Issue by pzmarzly** [sigmaSd/IRust#18]
`Ctrl+V` takes some time, as every character retriggers `racer`. It'd be nice to have it running in a separate (maybe cancel-able) thread.

**Comment by sigmaSd** [comment]
yeah I noticed it, I think the best idea is to add debouncing, hopefully its not that hard :)

**Comment by sigmaSd** [comment]
@pzmarzly would be great if you test out https://github.com/sigmaSd/IRust/commit/55a00e3b31a1cad5355083e5268a875168aee405

**Comment by pzmarzly** [comment]
Well, it is fast now, though autocomplete does not trigger after pasting (as due to synchronous nature of the event loop, it doesn't know if a character is the last one). I don't think it's that much of an issue, and changing that would require major changes to IRust. I'm fine with current state.

**Comment by sigmaSd** [comment]
Auto complete doesn't trigger after pasting cause I'm not using a real debouncer.
A real debouncer triggers the function after timer expires, something like this
```rust
use std::time::{Duration, Instant};

const WAIT_TIMEOUT: u64 = 50;

pub struct Debouncer {
    timer: Instant,
    function: Option<impl Fn>
}

impl Debouncer {
    pub fn new() -> Self {
        Self {
            timer: Instant::now(),
            function: None,
        }
    }

    pub fn start(&mut self) {
        std::thread::spawn(||{
            if self.timer.elapsed() >= Duration::from_millis(WAIT_TIMEOUT) {
                self.function;
            }
        })
    }
    pub fn run(&mut self, mut function: impl FnMut() -> std::io::Result<()>) {
        self.function = Some(function);
        self.timer = Instant::now();
    }
}
```
Then call `start()` at the begining of the program so it checks the timer all the time to know when it should trigger the callback
But Its not easy to implement I would need some guidance to make it work

**Comment by sigmaSd** [comment]
But I'm also satisfied with current result so we I think we should just leave this for the future^^
