### ISSUE TITLE
Remember :commands in history

### ISSUE THREAD

**Issue by pzmarzly** [sigmaSd/IRust#2]
Right now commands are added to history in `parse_second_order`, so commands like `:show`, `::ls` etc. are left out (cannot be repeated by `Up`->`Enter`). It would be nice to be able to have them in history (by having `self.history.push(self.buffer.drain(..).collect());` in `parse`). In case someone doesn't like that design, it could be a toggle-able option - but then we run into another issue: where should REPL configuration be stored? Bash uses `.bash_profile`, Python uses environmental variables.

**Comment by sigmaSd** [comment]
Hi, first of all thanks for opening these issues, these are my first ever xD
Back to the topic, indded this was a design choice to leave out non rust code, but I really like your idea I'll probably use `dirs` crate and use `config_dir()` that should solve the problem

**Comment by pzmarzly** [comment]
I agree on the idea of using `config_dir()`. I think you could use `toml` - here's some [code](https://github.com/pzmarzly/x11-input-mirror/blob/261dac624f093ce1c0fed9915a68a7f6d3f8f65e/src/config.rs#L36-L42) I wrote quite some time ago that uses it (of course you don't need any macro, irust will have 1 config file for now). I'll leave the decision and implementing it to you.

**Comment by sigmaSd** [comment]
Done https://github.com/sigmaSd/IRust/commit/d79163fff31efd2f998f1591950aef9bcae82314
@pzmarzly  Wanna review it? :)

**Comment by pzmarzly** [comment]
Sure, see #5 .

**Comment by pzmarzly** [comment]
Now that #5 is merged, all that's left is to mention the config file somewhere in README and to my mind this issue could then be closed.

**Comment by sigmaSd** [comment]
Ok Ill add it as soon as I can (tomorrow probably), thanks a lot for your work

**Comment by sigmaSd** [comment]
should be good now https://github.com/sigmaSd/IRust/commit/51ef8a96fecbcb383680e8cb5815ec60c64171a1
