### ISSUE TITLE
Suggestions are non-deterministic

### ISSUE THREAD

**Issue by pzmarzly** [sigmaSd/IRust#23]
Hitting `a` -> `Backspace`:

![deepin-screen-recorder_xfce4-terminal_20190603200530](https://user-images.githubusercontent.com/8074163/58823905-17ae4480-863b-11e9-83cd-fddeec96c644.gif)

**Comment by sigmaSd** [comment]
Do we want to fix that, hitting tab give you all the sugesstions anyway, what do you think ?

**Comment by sigmaSd** [comment]
And btw its not really undeterministic, its just that writing sugesstion uses racer.next_sugesstion fn which changes the current suggestion, I guess I can lock it but Im not sure it really matters

**Comment by pzmarzly** [comment]
I don't think it's important, but if all that needs to be done is to sort Racer suggestions at some point, or reset some counter, then maybe you could quickly fix it.

**Comment by sigmaSd** [comment]
Well I spent time on this, its not easy there are a lot of race conditions between de-bouncer and main-thread, I need a new design to fix the root issue

**Comment by sigmaSd** [comment]
Would you test https://github.com/sigmaSd/IRust/tree/racer3.0

**Comment by sigmaSd** [comment]
thanks for the detailed issue!
should be good https://github.com/sigmaSd/IRust/commit/d6fb300729cdb52ca51427fc4672ca837ad08d09

**Comment by pzmarzly** [comment]
Here's a remaining minor issue:

![deepin-screen-recorder_xfce4-terminal_20190605195732](https://user-images.githubusercontent.com/8074163/58978489-355ee380-87cc-11e9-89a9-f77d2e222962.gif)

Otherwise, I found none.

**Comment by sigmaSd** [comment]
thans again! https://github.com/sigmaSd/IRust/commit/c2c16c842f51d7b45b26c949c758971100617c82

**Comment by sigmaSd** [comment]
Ah issue still present

**Comment by sigmaSd** [comment]
should be good now https://github.com/sigmaSd/IRust/commit/1ac61b4dddfe175390649aefcc84cb886c303964

**Comment by sigmaSd** [comment]
Feel free to reopen if you encounter other issues
