### ISSUE TITLE
Terminal output display missing after quitting IRust

### ISSUE THREAD

**Issue by tobz1000** [sigmaSd/IRust#36]
Issue experienced with Bash 4.4.9 and the following terminal emulators:
- LXTerminal 0.3.1
- Guake 3.0.5
- xterm 330

To reproduce:

1. Start `irust`
2. Close with ctrl-d or ctrl-c
3. Start typing in parent shell

My typed command does not display in the terminal. If I press enter, the command output is displayed; however, line breaks do not return to the start of the line.

Here is a correctly-displayed `ls`:
![2019-07-11-124428_736x468_scrot](https://user-images.githubusercontent.com/1471978/61048462-cb90b580-a3d9-11e9-81f2-eaa2a413b521.png)

Here is the result of `ls` after closing IRust:
![2019-07-11-124457_736x449_scrot](https://user-images.githubusercontent.com/1471978/61048484-d8150e00-a3d9-11e9-922e-830b439081e4.png)

**Comment by pzmarzly** [comment]
At first I thought it may be a bug in `crossterm::Terminal::exit()` but it's just a wrapper for `std::process::exit(0)`. Could you try running:

```bash
irust && stty sane
irust && tput clear
irust && tput reset
```

Hopefully at least 1 of these commands should help, and knowing which one does should help sigmaSd fix the issue.

**Comment by tobz1000** [comment]
Thanks! `stty sane` and `tput reset` fix the issue (only one is needed). `tput clear` doesn't make any difference. Hopefully that helps with a diagnosis...

Let me know if you'd like any more testing.

**Comment by sigmaSd** [comment]
Hi @tobz1000  @pzmarzly,  I should hopefully have time to look into it tomorrow,
thx for helping @pzmarzly!

**Comment by sigmaSd** [comment]
@tobz1000 https://github.com/sigmaSd/IRust/commit/5fe3a57ce55cf86b838ba27b411abaaad4275c17
Its weird that this fixs it, since terminal.exit() does the same thing, I'll probably dig deeper

**Comment by tobz1000** [comment]
Yep - the patch fixes it, thanks!

Yeah, `Terminal::exit` is a bit of weird one, pretty much a re-export of `sys::exit`. But I guess since `Terminal` doesn't own/know about any `RawScreen`, it doesn't try to guess the current or previous terminal state.

**Comment by sigmaSd** [comment]
@tobz1000 I like your idea! I'll keep it in mind for now
