### ISSUE TITLE
Warn about expressions with empty output

### ISSUE THREAD

**Issue by smolck** [sigmaSd/IRust#39]
Currently, after entering something like this into the REPL:
```rust
fn test(args: i32) -> i32 {
    println!("You entered {}.", args);
    return args * 3;
}
```
When trying to run it with `test(3)`, I get an error:
```
In: test(3)

error[E0425]: cannot find function `test` in this scope
 --> src/main.rs:3:2
  |
3 |     test(3)
  |     ^^^^ not found in this scope
```

If I put a semicolon at the end of `test(3)`, so that it becomes `test(3);`, I get no output from the REPL, and when I type `:show`, I get this:
```rust
In: test(3);
In: :show
Current Repl Code:
fn main() {
    test(3);
}
```

Is the ability to define functions within the REPL currently not a feature, or am I missing something? If it isn't a feature, is it wanted? If so, I would be happy to help with the implementation where I can.

**Comment by sigmaSd** [comment]
Hi @smolck! You need to put a semi colon after the function definition, like `fn a(4) {};`

The way you wrote it actually should trigger a warning, `irust: are you missing a ;` 
Didnt the error msg appear in your case?

**Comment by sigmaSd** [comment]
In the same vein https://github.com/sigmaSd/IRust/issues/8

I think @pzmarzly is right about the sirprising behaviour,

Ah nvm about the error msg it wouldnt trigger in your case, but maybe I should add more agressive warnings (maybe each time the output is ())

**Comment by sigmaSd** [comment]
If you're interested you can add some analysis here https://github.com/sigmaSd/IRust/blob/master/src/irust/format.rs#L28

**Comment by smolck** [comment]
@sigmaSd Thanks!

> If you're interested you can add some analysis here https://github.com/sigmaSd/IRust/blob/master/src/irust/format.rs#L28

Thanks, I'll look into it for sure! Beyond adding a warning message if the user doesn't put a semicolon at the end of a function definition, what other warnings would you like added?

**Comment by sigmaSd** [comment]
Thanks!

Better keep it open until atleast we add a warning about this particular case cause I bet its frequent

If you figure out other warning cases feel free to add them as well or we'll just add them as they come up

**Comment by sigmaSd** [comment]
@smlock, Hope its alright that I implemented this https://github.com/sigmaSd/IRust/commit/c2075b5be8a35eebc7a09dabc6adeadc3666deba, 
I just removed the input analysis, and now IRust warns about all expressions that returns a "()" (except for empty input, in that case it just create a new line)

Also I added this patch https://github.com/sigmaSd/IRust/commit/4f650fca01ab054c62753528f22fdeb7323ae0df to disable cargo warnings, It feels they are out of place in a repl

**Comment by smolck** [comment]
That’s great, thanks! As a side note, do you have any other features you’d like to see implemented? I’m happy to help where I can.

**Comment by sigmaSd** [comment]
@smolck  ,thanks a lot for your offer!

There are a lot of things that could be done(both bug fixes, and features), I'll write appropriate issues, (obviously if you notice something, feel free to open an issue as well!)

Currently a feature I really want is highlighting the input, 
My last try was by using syntect, pseudo-code:
https://github.com/sigmaSd/IRust/blob/master/src/irust/events.rs#L9
```rust
fn handle_character() {
    let input = highlight(self.buffer);
    self.write(input);
}
```
*highlight function https://github.com/sigmaSd/IRust/blob/master/src/irust/highlight.rs#L7*

The problem with this approach is that its slow, and it makes the input laggy, not sure if I'm using syntect the right way, or if I should look for a different design to solve this problem

**Comment by smolck** [comment]
Interesting. The highlighting is quick with `:show`, so I imagine that when `highlight()` is called for each char, the allocated memory per char starts to slow things down. I've opened a new issue, #40, to focus discussion on how we implement this new feature.
