### ISSUE TITLE
Add `:irust` command

### ISSUE THREAD

**Issue by sigmaSd** [sigmaSd/IRust#49]
It will print Ferris ASCII art, would be great if its animated, but I accept statics too ^^

**Comment by smolck** [comment]
You mean stuff like this animated ASCII ferris?

https://jsfiddle.net/Diggsey/3pdgh52r/embedded/result/

**Comment by sigmaSd** [comment]
Ha thats cool, yeah that can work

**Comment by sigmaSd** [comment]
placeholder https://github.com/sigmaSd/IRust/blob/master/src/irust/parser.rs#L175

**Comment by jadijadi** [comment]
May I work on this dear @sigmaSd

**Comment by sigmaSd** [comment]
Hi @jadijadi, of course  would be great!

**Comment by jadijadi** [comment]
Dear @sigmaSd , there are two variations of Ferris.

1)
```
█ █         █ █
▀█  ▄█████▄  █▀
 ▀▄███▀█▀███▄▀ 
 ▄▀███▀▀▀███▀▄ 
 █ ▄▀▀▀▀▀▀▀▄ █ 
```

and 2)
```
     _~^~^~_
 \) /  o o  \ (/
   '_   ¬   _'
   / '-----' \
```

Both look nice ('ve tried them). 

1. which one? 1 or 2 or random? :)
2. should I keep the current IRUST in ascii art? or its just a place holder?
3. I think it is good if we move this ASCII ART function to arts.rs . will be cleaner. 
4. If fine, I'll commit a fixed logo first.

**Comment by sigmaSd** [comment]
Hah 1 looks scarier to me :p, thanks a lot @jadijadi  for working on this btw
1- random I like both
2 - its just a place holder so you can remove it
3 - I defenitly agree it belongs to art.rs
4 - sure

**Comment by sigmaSd** [comment]
fixed by  https://github.com/sigmaSd/IRust/pull/59
