### ISSUE TITLE
add tab completion

### ISSUE THREAD

**Issue by D1mon** [sigmaSd/IRust#51]

**Comment by sigmaSd** [comment]
Hi @D1mon tab completion is already supported if you have racer installed

**Comment by sigmaSd** [comment]
I guess I can close this then

**Comment by D1mon** [comment]
yes

**Comment by D1mon** [comment]
Look towards "pry" (ruby) and add the features that are there.

**Comment by sigmaSd** [comment]
interesting I'll check it out
