### ISSUE TITLE
thread 'main' panicked at 'IRust Out: IoError

### ISSUE THREAD

**Issue by D1mon** [sigmaSd/IRust#52]
rustc --version
`rustc 1.40.0-nightly (8431f261d 2019-09-29)`

cargo --version
`cargo 1.39.0-nightly (ab6fa8908 2019-09-25)`

>  ------------------------------------------------------------------------------Welcome to IRust------------------------------------------------------------------------------
> 
> In: 1thread 'main' panicked at 'IRust Out: IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })', src/libcore/result.rs:1165:5
> stack backtrace:
>    0:     0x555efef13cb4 - backtrace::backtrace::libunwind::trace::h92f4bca147eaf003
>                                at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
>    1:     0x555efef13cb4 - backtrace::backtrace::trace_unsynchronized::hab0c9829cb374bd1
>                                at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
>    2:     0x555efef13cb4 - std::sys_common::backtrace::_print_fmt::h7de186026ed9cfd7
>                                at src/libstd/sys_common/backtrace.rs:76
>    3:     0x555efef13cb4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h72c9014a6d4c17fe
>                                at src/libstd/sys_common/backtrace.rs:60
>    4:     0x555efef3862c - core::fmt::write::he8debf927fa26231
>                                at src/libcore/fmt/mod.rs:1028
>    5:     0x555efef10a27 - std::io::Write::write_fmt::h6c8e4c259b547329
>                                at src/libstd/io/mod.rs:1412
>    6:     0x555efef168c5 - std::sys_common::backtrace::_print::ha816fdd57a919bae
>                                at src/libstd/sys_common/backtrace.rs:64
>    7:     0x555efef168c5 - std::sys_common::backtrace::print::hafeee729c9a72709
>                                at src/libstd/sys_common/backtrace.rs:49
>    8:     0x555efef168c5 - std::panicking::default_hook::{{closure}}::h1ef6174970e041c9
>                                at src/libstd/panicking.rs:196
>    9:     0x555efef165b6 - std::panicking::default_hook::he3bfe887c04a1755
>                                at src/libstd/panicking.rs:210
>   10:     0x555efef16fc5 - std::panicking::rust_panic_with_hook::h5fc80d9ca9339a9b
>                                at src/libstd/panicking.rs:473
>   11:     0x555efef16b62 - std::panicking::continue_panic_fmt::hda34f456b7fc6f05
>                                at src/libstd/panicking.rs:380
>   12:     0x555efef16a56 - rust_begin_unwind
>                                at src/libstd/panicking.rs:307
>   13:     0x555efef350fa - core::panicking::panic_fmt::hcefc03686fff269e
>                                at src/libcore/panicking.rs:84
>   14:     0x555efef351f7 - core::result::unwrap_failed::h3e69de8175c25305
>                                at src/libcore/result.rs:1165
>   15:     0x555efeeb39e8 - irust::main::h26081b34c2cdf82d
>   16:     0x555efeeb0553 - std::rt::lang_start::{{closure}}::h0b57e810707ed2f3
>   17:     0x555efef169f3 - std::rt::lang_start_internal::{{closure}}::h5eb6ace3eb8dd1aa
>                                at src/libstd/rt.rs:49
>   18:     0x555efef169f3 - std::panicking::try::do_call::hba48a9e439683bd0
>                                at src/libstd/panicking.rs:292
>   19:     0x555efef1e1da - __rust_maybe_catch_panic
>                                at src/libpanic_unwind/lib.rs:80
>   20:     0x555efef174bd - std::panicking::try::h469d0537aa9e7942
>                                at src/libstd/panicking.rs:271
>   21:     0x555efef174bd - std::panic::catch_unwind::hb22bce686f9d3206
>                                at src/libstd/panic.rs:394
>   22:     0x555efef174bd - std::rt::lang_start_internal::h8453f9cea0010827
>                                at src/libstd/rt.rs:48
>   23:     0x555efeeb3a52 - main
>   24:     0x7f68ff424ee3 - __libc_start_main
>   25:     0x555efee8121e - _start
>   26:                0x0 - <unknown>

install clean rust nightly and run 'cargo install racer irust'

**Comment by sigmaSd** [comment]
which os os, terminal?
does it not happen with stable rust?
I remember facing this error with windows 7 but I didn't investigate further, its an upstream issue it happens when racer is on, that's why racer option is disabled by default on windows

**Comment by D1mon** [comment]
Manjaro
Yakuake (Konsole)

**Comment by D1mon** [comment]
when I got 1.37 - everything worked except tab completion. then I posted nightly and racer and now it doesn’t work

**Comment by sigmaSd** [comment]
for now you can just install racer with nightly, and install irust with stable to workaround the issue, I'll try to reproduce it in the meantime

**Comment by D1mon** [comment]
racer is not installed on the stable version, says that you need to install nightly

**Comment by sigmaSd** [comment]
cargo +nightly install racer
cargo +stable install irust

**Comment by sigmaSd** [comment]
so in your case you already installed racer, so just remove irust and install it with stable

**Comment by D1mon** [comment]
does not work. I will try tomorrow

**Comment by sigmaSd** [comment]
I did reproduce your error, I have a general idea about whats happening but I wont try to fix it until this issue affects stable since it could be just a nighlty bug,
Just to recap this should work: 
1- install racer with nightly: cargo +nightly install racer
2- install irust with stable: cargo +stable install irust (make sure you already removed the old version)

If you still encounter an issue post it here

**Comment by sigmaSd** [comment]
I figured out the issue, racer needs to be properly configured for different cargo channel,
so to complete the steps in my last comment
step 3: make sure racer is correctly configured: https://github.com/racer-rust/racer#configuration `rustup component add rust-src`

**Comment by D1mon** [comment]
works!!! completed the team and it all worked! Thank.

**Comment by D1mon** [comment]
works!!! Thank.
