### ISSUE TITLE
Add confirmation dialog when quitting with Ctrl-D

### ISSUE THREAD

**Issue by sigmaSd** [sigmaSd/IRust#54]
exp: Do you really want to exit ([y]/n)?

**Comment by jadijadi** [comment]
Hi @sigmaSd , May I work on this?

**Comment by sigmaSd** [comment]
Hi @jadijadi ! Would be great, feel free to ask any question needed

**Comment by jadijadi** [comment]
Dear @sigmaSd , thanks for the opportunity. Very cool project. Thumbs up!
Checking the code, I can say that I have to insert my code into `events.rs`, at `pub fn handle_ctrl_d`. I will use your `write_newline` and `write` but I did not figured out how I should read the keyboard input from the user. Should I user your buffer? Can you please give me a hint.

**Comment by sigmaSd** [comment]
thanks as well for taking the time to contribute!
Its not very clear to me as well,
maybe one way to solve this is to have a mini event loop like 
```rust
let mut stdin = TerminalInput::new().read_sync();
let awnser = String::new();
if let Some(key_event) = stdin.next() {
    loop {
        write(question);
        match key_event {
            InputEvent::Keyboard(KeyEvent::Char(c)) => {
                answer.push(c);
                write(c);
            }
            InputEvent::Keyboard(KeyEvent::Enter) => match answer {
                y | yes => quit,
                n => return,
                _ => continue,
            },
        }
    }
}
```

**Comment by jadijadi** [comment]
Dear @sigmaSd , I've sent a PR for this, please feel free to comment or ask for any changes.

**Comment by sigmaSd** [comment]
fixed by https://github.com/sigmaSd/IRust/pull/57
