### ISSUE TITLE
Can't get to work on Windows

### ISSUE THREAD

**Issue by fdncred** [sigmaSd/IRust#66]
I can write your factorial function in the readme and it accepts it but when I try to execute it or do just about anything, I get this error message.
`The system cannot find the file specified. (os error 2)`

I installed everything it asked to install on the first run. What can I try next?

**Comment by sigmaSd** [comment]
Hi! Can you check if ℅Temp%/irust/target/debug/irust.exe exists? Also which version of windows you're on?

**Comment by sigmaSd** [comment]
Btw I'm suspicious its an antivirus interfering.

**Comment by fdncred** [comment]
version: Microsoft Windows [Version 10.0.19041.508]
no, that debug/irust.exe does not exist.

```
Directory: C:\Users\username\AppData\Local\Temp\irust

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           9/21/2020 11:12 AM                src
-a---           9/21/2020 11:12 AM            136 Cargo.lock
-a---           9/21/2020  1:16 PM             59 Cargo.toml
-a---           9/21/2020 11:26 AM            186 fmt_file
```

This is with virusscan turned off.
![image](https://user-images.githubusercontent.com/343840/93805447-63f50d80-fc0d-11ea-9335-f5de3db8de09.png)

**Comment by sigmaSd** [comment]
I don't have a win 10 machine currently, If you would like  debug you can:
test 1 - add a `dbg!(output)` here https://github.com/sigmaSd/IRust/blob/master/src/irust/cargo_cmds.rs#L63
and run something(5+4)

test 2-  run somthing on irust (5+4) then cd to `%temp%/irust/` and run `cargo run` to check if that works

**Comment by sigmaSd** [comment]
Its weird that you don't have the target directory, it should be created immediately when irust is run,
I think you should try test2 it might be something with the tool-chain you have.

**Comment by sigmaSd** [comment]
I still suspect there is something interfering, irust when run:
1 - create %temp%/irust folder
2 - run `cargo build` on it, we know that this command succeeded since now you have src, cargo.toml, etc.. , but it should also create target folder and the executable in it, so my suspicion it got removed after since you don't have it.

**Comment by fdncred** [comment]
oh, I think I may have just figured it out. I have the `CARGO_TARGET_DIR` environment variable set which make cargo put the target dir wherever that env var is set to.

**Comment by fdncred** [comment]
yup, i temporarily disabled that env var and can do this now.

![image](https://user-images.githubusercontent.com/343840/93810566-7757a700-fc14-11ea-8d26-b0e80aafaf6e.png)

**Comment by sigmaSd** [comment]
Nice find! Ill be sure to handle that case then.

**Comment by sigmaSd** [comment]
Should be fixed now https://github.com/sigmaSd/IRust/commit/c799f7ab4a6caa5826e2ef8ff50fc9bfb5c78079

**Comment by fdncred** [comment]
Looks like we still need a few more tweaks, although I assume this is unrelated.

```
cargo b --release
   Compiling winapi v0.3.9
   Compiling proc-macro2 v1.0.18
   Compiling syn v1.0.34
   Compiling serde v1.0.116
   Compiling scopeguard v1.1.0
   Compiling smallvec v1.4.1
   Compiling lock_api v0.3.4
   Compiling quote v1.0.7
   Compiling parking_lot_core v0.7.2
   Compiling dirs-sys-next v0.1.0
   Compiling crossterm_winapi v0.6.1
   Compiling dirs-next v1.0.1
   Compiling serde_derive v1.0.116
   Compiling parking_lot v0.10.2
   Compiling toml v0.5.6
   Compiling crossterm v0.17.8
   Compiling irust v0.8.17 (C:\Users\username\source\repos\forks\IRust)
error[E0603]: module `ansi_support` is private
   --> src\irust\cargo_cmds.rs:116:31
    |
116 |     let color = if crossterm::ansi_support::supports_ansi() {
    |                               ^^^^^^^^^^^^ private module
    |
note: the module `ansi_support` is defined here
   --> C:\Users\username\.cargo\registry\src\github.com-1ecc6299db9ec823\crossterm-0.17.8\src/lib.rs:251:1
    |
251 | pub(crate) mod ansi_support;
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0603`.
error: could not compile `irust`.

To learn more, run the command again with --verbose.
error: External command failed
  ┌─ shell:1:1
  │
1 │ cargo b --release
  │ ^^^^^ command failed
```

It looks like `is_ansi_code_supported()` is available on `Command` but I'm not sure how to call it.

**Comment by sigmaSd** [comment]
Yeah im using crossterm git features for the master branch, you can change that in Cargo.toml, The next release of crossterm should be soon thats why I left it like I that.

**Comment by sigmaSd** [comment]
But Ill update it for consistency.

**Comment by fdncred** [comment]
Thanks for this change. It compiles now. I may open other issues. I love the UI, love how to control the cursor when re-editing functions, love the syntax highlighting, love how tabbing works right. Don't like a few things as well. :)

**Comment by sigmaSd** [comment]
@fdncred thanks as well!  Sure that would be great!
