### ISSUE TITLE
how make irust works with nightly ? error: toolchain 'stable-x86_64-unknown-linux-gnu' is not installed

### ISSUE THREAD

**Issue by D1mon** [sigmaSd/IRust#75]

**Comment by sigmaSd** [comment]
Hello,

You can edit the configuration file https://github.com/sigmaSd/IRust#configuration `toolchain="nightly"`

Also you can while running irust use this command `:toolchain nightly` (it will edit the configuration)

**Comment by D1mon** [comment]
Thanks
