### ISSUE TITLE
Async repl not working properly

### ISSUE THREAD

**Issue by NobodyXu** [sigmaSd/IRust#90]
During the async mode (I was using `tokio` runtime), no matter what I enters, `irust` just silently accepts them without printing any result, even for the most simple expression `1 + 2`.

**Comment by sigmaSd** [comment]
Hello, that area indeed needs better error reporting

Usually to debug this, you can after inputing something to the repl and hitting enter, go to /tmp/irust_host_repl and run cargo r and it will show the error ( I suspect cargo add failed)

**Comment by sigmaSd** [comment]
thanks for the bug report turns out it an actual issue, fixed in https://github.com/sigmaSd/IRust/commit/5de6c9f68c2e18bcb230b6f912d599f43e077f46

**Comment by sigmaSd** [comment]
Actually I'll keep the issue open till next release

**Comment by NobodyXu** [comment]
Thank you so much for the quick response!

**Comment by sigmaSd** [comment]
You're welcome!
